

CREATE TABLE APP.Client(
      client_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
      login varchar(100) NOT NULL,
      CONSTRAINT primary_key PRIMARY KEY (client_id)
);

ALTER TABLE APP.Client
ADD CONSTRAINT login_UNIQUE UNIQUE (login);

CREATE TABLE APP.History
(
	history_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	from_ integer NOT NULL,
	to_ integer NOT NULL,
	date_ DATE NOT NULL,
	message varchar(1000) NOT NULL,
	CONSTRAINT HISTORY_PK PRIMARY KEY (history_id)
);

ALTER TABLE APP.History
ADD CONSTRAINT from_HISTORY_FK FOREIGN KEY (from_)
REFERENCES APP.Client(client_id);

ALTER TABLE APP.History
ADD CONSTRAINT to_HISTORY_FK FOREIGN KEY (to_)
REFERENCES APP.Client(client_id);